# Generated by Django 5.0.3 on 2024-03-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('profile_image', models.ImageField(upload_to='')),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
